-- clean and transform data 
-- alter chargingpoint_status data type to text
ALTER TABLE ev_main
ALTER COLUMN chargingpoint_status TYPE TEXT;
-- update status to occupied for chargingpoint_status = 0
UPDATE ev_main
SET chargingpoint_status = 'OCCUPIED'
WHERE chargingpoint_status = '0';

-- update status to available for chargingpoint_status = 1
UPDATE ev_main
SET chargingpoint_status = 'AVAILABLE'
WHERE chargingpoint_status = '1';

-- update status to not available for chargingpoint_status = 100
UPDATE ev_main
SET chargingpoint_status = 'NOT AVAILABLE'
WHERE chargingpoint_status = '100';

-- alter evid_status data type to text
ALTER TABLE ev_main
ALTER COLUMN evid_status TYPE TEXT;
-- update status to occupied for evid_status = 0
UPDATE ev_main
SET evid_status = 'OCCUPIED'
WHERE evid_status = '0';

-- update status to available for evid_status = 1
UPDATE ev_main
SET evid_status = 'AVAILABLE'
WHERE evid_status = '1';

-- update status to not available for evid_status = null
UPDATE ev_main
SET evid_status = 'NOT AVAILABLE'
WHERE evid_status IS NULL;

-- alter price_type data type to text
ALTER TABLE ev_main
ALTER COLUMN price_type TYPE TEXT;
-- update price_type 'h' to 'PER HOUR' 
UPDATE ev_main
SET price_type = 'PER HOUR'
WHERE price_type = 'h';

-- update price_type 'kWh' to 'PER KILO WATT HOUR' 
UPDATE ev_main
SET price_type = 'PER KILO WATT HOUR'
WHERE price_type = 'kWh';

-- update price_type 'free' to 'FREE' 
UPDATE ev_main
SET price_type = 'FREE'
WHERE price_type = 'free';

---------------------------------------------------------------------------------------------------------------
-- loading transformed data to new tables
-- create table for location, copy data from ev_main, set primary and foreign key
DROP TABLE IF EXISTS dim_location;
CREATE TABLE dim_location (
	postal_code INTEGER PRIMARY KEY,
	address TEXT,
	location_name TEXT,
	longtitude DOUBLE PRECISION,
	latitude DOUBLE PRECISION
	);

INSERT INTO dim_location
SELECT DISTINCT postal_code, address, location_name, longtitude, latitude
FROM ev_main;

ALTER TABLE ev_main
ADD CONSTRAINT postal_code_key FOREIGN KEY (postal_code) REFERENCES dim_location (postal_code);

ALTER TABLE ev_main
DROP COLUMN address
	
ALTER TABLE ev_main
DROP COLUMN location_name;

ALTER TABLE ev_main
DROP COLUMN longtitude;

ALTER TABLE ev_main
DROP COLUMN latitude;


-- create table operator, copy data from ev_main, set foreign and primary key
DROP TABLE IF EXISTS dim_operator;
CREATE TABLE dim_operator (
	operator_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	operator TEXT);

INSERT INTO dim_operator (operator)
SELECT DISTINCT operator
FROM ev_main;

ALTER TABLE ev_main
ADD COLUMN operator_id INTEGER REFERENCES dim_operator (operator_id);

UPDATE ev_main
SET operator_id = dim_operator.operator_id
FROM dim_operator
WHERE ev_main.operator = dim_operator.operator;

-- create table charger, copy data from ev_main, set foreign and primary key
DROP TABLE IF EXISTS dim_charger;
CREATE TABLE dim_charger (
	charger_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	plug_type TEXT,
	current VARCHAR(3),
	price_type TEXT);

INSERT INTO dim_charger (plug_type, current, price_type)
SELECT DISTINCT plug_type, current, price_type
FROM ev_main
GROUP BY plug_type, current, price_type;

ALTER TABLE ev_main
ADD COLUMN charger_id INTEGER REFERENCES dim_charger (charger_id);

UPDATE ev_main
SET charger_id = dim_charger.charger_id
FROM dim_charger
WHERE ev_main.plug_type = dim_charger.plug_type
	AND ev_main.current = dim_charger.current
	AND ev_main.price_type = dim_charger.price_type;

-- set primary key for evcp_id
ALTER TABLE ev_main
ADD CONSTRAINT evcp_id_pkey PRIMARY KEY (evcp_id);

-- dropping irrelevant columns in ev_main
ALTER TABLE ev_main
DROP COLUMN chargingpoint_status;

ALTER TABLE ev_main
DROP COLUMN operating_hours;

ALTER TABLE ev_main
DROP COLUMN operator;

ALTER TABLE ev_main
DROP COLUMN chargingpoint_name;

ALTER TABLE ev_main
DROP COLUMN plug_type;

ALTER TABLE ev_main
DROP COLUMN current;

ALTER TABLE ev_main
DROP COLUMN price_type;

-- alter postal_code data type to varchar(6) for table ev_main and dim_location
ALTER TABLE ev_main
DROP CONSTRAINT postal_code_key;

ALTER TABLE ev_main
ALTER COLUMN postal_code TYPE VARCHAR(6);

ALTER TABLE dim_location
ALTER COLUMN postal_code TYPE VARCHAR(6);

UPDATE dim_location
SET postal_code = CONCAT('0', postal_code)
WHERE LENGTH(postal_code) < 6;

UPDATE ev_main
SET postal_code = CONCAT('0', postal_code)
WHERE LENGTH(postal_code) < 6;

ALTER TABLE ev_main
ADD CONSTRAINT postal_code_fkey FOREIGN KEY (postal_code) REFERENCES dim_location (postal_code);

-- problem statement: how many ev chargers are there in my area and whether i should buy EV?
WITH evcp_east AS (
SELECT LEFT(postal_code, 2) AS postal_prefix, COUNT(*) AS total_evcp
FROM ev_main
WHERE LEFT(postal_code, 2) IN ('42', '43', '44', '45', '46', '47', '48', '49', '50', '81', '51', '52')
GROUP BY postal_prefix
ORDER BY postal_prefix
)

SELECT SUM(total_evcp) AS total_evcp_east
FROM evcp_east

/* challenges:
- setting the correct data types at the start. i realise i keep changing the data type after loading to accomodate in order to insert new data.
- difficulty on how best to design the database in view of the normalization and foreign keys.
*/
